---
- name: Update SNOW with ADSP Data
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: include vars
    include_vars: change_request_vars.yml

  - name: Parse ADSP CSV Content to ServiceNow Table
    snow_record:
      state: present
      table: u_adsp_csv
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      data:
        u_client_mac: "{{ sn_severity }}"
        u_vendor: "{{ sn_priority }}"
    register: new_adsp

  - debug: 
      var: new_adsp.record
